name: 'social-api'
host: '192.168.31.164'
port: 8848
social_srv:
  host: '192.168.123.150'
  port: 8100
  name: 'social-srv'

redis:
  host: ''

consul:
  host: '192.168.123.150'
  port: 8500

jwt:
  key: ''