name: 'social-api'
host: '10.0.16.7'
port: 8848
social_srv:
  host: '10.0.16.7'
  port: 8100
  name: 'social-srv'

redis:
  host: ''

consul:
  host: '124.221.120.88'
  port: 8500

jwt:
  key: 'pkNbjcn4C5g'
  token_expires_time: 86400