# 主服务器地址
MainServerAddress: http://121.37.98.68
MainServerPort: 8080

# GRPC服务器地址
GRPCServerAddress: localhost
GRPCServerPort: 50051

# MySQL服务地址
MySQLAddress: 121.37.98.68
MySQLPort: 3306
MySQLUserName: dymysql
MySQLPassword: gxnw21XxRhY
MySQLDataBase: simpledy

# 静态资源服务器
NginxAddress: http://121.37.98.68
NginxPort: 81
StaticPath: /root/MyTiktok-Resource/ # 静态资源地址
VideoPath: videos/ # 视频存放地址
ImagePath: images/ # 图片存放地址