name: 'social-srv'
mysql:
  host: '121.37.98.68'
  port: 3306
  db: 'simpledy'
  user: 'dymysql'
  password: 'gxnw21XxRhY'

consul:
  #host: '192.168.123.150'
  #host: '124.221.120.88'
  host: '121.37.98.68'
  port: 8500